server:
  port: 8088

me:
  linbo:
    web:
      security-key: 9KZobY7maVd1lkiPyNh8TzrWMOQSUgCD0FBxtqX62AnGs35fLeEHIpc4jRvJuwLv41tWbrlfUCjP1fmkx1FLOnqjpdTRJEkhd6DmA1LsG5IFoHMyRSIAntHpKCMcZV35
      expiration-time: 1000*60*60*24


# DataSource Config
spring:
  datasource:
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:p6spy:mysql://127.0.0.1:3306/api?Unicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#    username: root
#    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/api?Unicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
  jackson:
    serialization:
      write-dates-as-timestamps: true
    date-format: y
  http:
    converters:
    encoding:
      charset: UTF-8
      force: true

mybatis-plus:
  configuration:
    cache-enabled: true
  global-config:
    worker-id: 1
    datacenter-id: 1
  mapper-locations: classpath*:/mapper/*/*.xml


logging:
  level:
    me:
      linbo:
        web: debug
    org:
      springframework:
        security: debug